
Apreciado Propietario del Certificado __CERT_SERIAL__,

El certificado con el serial __CERT_SERIAL__ y el asunto 
__CERT_SUBJECT__ va a vencer el  __CERT_NOTAFTER__.
El certificado fue emitido para __CERT_CN__.

Por favor visite nuestra pagina para solicitar un nuevo
certificado o contacte nuestra autoridad de registro para
renovar el certificado.
Ud. puede simplemente responder esta correo para infomacion
adicional

@httpd_protocol@://@httpd_host@@httpd_port@

Por favor recuerde que los servicios para los cuales el 
certificado es usado probablemente dejaran de funcionar este
certificado vence.

				Cordial Saludo, 
				@ca_organization@ Security Staff.
