#! /opt/local/bin/perl

$VER = '0.1.0';

## User Management Tool for OpenCA 1.2.0+
## (c) 1999-2010 by Massimiliano Pala and OpenCA Labs
##     All Rights Reserved
##
## Description:
## ============
##
##

use lib '/usr/local/lib/openca/perl_modules/perl5';

use OpenCA::User;

print "\n  OpenCA User Management - Version $VER\n";
print "  (c) 1999-2010 by Massimiliano Pala and OpenCA Labs\n";
print "  OpenCA Licensed software\n\n";

my @keys = @ARGV;

my $db_type = "mysql";
my $db_user = "openca";
my $db_name = "openca";
my $db_host = "localhost";
my $db_port = "3306";
my $db_passwd = "openca";
my $db_namespace = "";

my $usr = OpenCA::User->new (
	DB_Type => $db_type,
	DB_User => $db_user,
	DB_Host => $db_host,
	DB_Port => $db_port,
	DB_Name => $db_name,
	DB_Passwd => $db_passwd,
	DB_Namespace => $db_namespace,
	DEBUG => 1,
);

my $user = {
	USER_ID => "pala@cs.dartmouth.edu",
	STATUS  => "VALID",
	NOTBEFORE => "201003162143",
};

$usr->add ( USER => $user );

my $p = $usr->get ( USER_ID => $user->{USER_ID} );

$usr->debug("DB=>" . $p->{USER_ID});



exit 0;
