Spoštovani lastnik certifikata __CERT_SERIAL__,


certifikata s serijsko številko __CERT_SERIAL__ in subjektom __CERT_SUBJECT__ bo potekel dne __CERT_NOTAFTER__. 
Certifikat je bil izdan za __CERT_CN__.

Prosimo, obiščite našo spletno stran in oddajte zahtevek za nov certifikat ali stopite v stik z nami in zahtevajte obnovitev vašega certifikata. Če želite, lahko odgovorite kar na to sporočilo in zahtevate nadaljnja pojasnila.

@httpd_protocol@://@httpd_host@@httpd_port@

Prosimo, upoštevajte da storitve, za katero ste uporabljali vaš certifikat, ne boste mogli več uporabljati, ko bo certifikat dokončno potekel.


Lep pozdrav, 
@ca_organization@ varnostna ekipa.
