Spoštovani,

Vaš certifikat s serijsko številko @__SERIAL__@ in DN @__DN__@ je bil generiran. Z našega strežnika ga lahko posnamete na sledečem naslovu:

	@httpd_protocol@://@httpd_host@@httpd_port@

Prosimo, uporabite sledeči PIN, ko boste želeli preklicati certifikat:

$PIN

(V kolikor certifikata v tem trenutku ne želite preklicati, si številko PIN shranite na varno mesto, za poznejšo uporabo.)

Lep pozdrav,
@ca_organization@ varnostna ekipa.
