<div class="home_content">
  <p class="title" @TITLE_STYLE@ >
	<!-- 
     <span style="font-size: 0.8em;">
       Welcome to
     </span><br />
	-->
     @ORGANIZATION@ PKI
  </p>
  <div style="padding: 10px; text-align: justify; margin-bottom: 15px;">
  <p>
	<h3>Welcome to @ORGANIZATION@!</h3>
	@ORGANIZATION@ is a organization of volunteers who provide Open-Source
        software for managing digital identities. The @ORGANIZATION@ hosts
	many security-related projects like
	<a href="http://www.openca.org/projects/libpki">LibPKI</a>,
	<a href="http://www.openca.org/projects/prqpd">PRQP server</a>,
	<a href="http://www.openca.org/projects/ocspd">OCSP server</a>, and
	<a href="http://www.openca.org/projects/openca">OpenCA PKI</a>.
	Our 
	<a href="http://en.wikipedia.org/wiki/Certificate_authority">
	Certification Authority</a> provides services for generating and 
	managing your 
	<a href="http://en.wikipedia.org/wiki/Digital_Certificate">
	Digital Certificates</a>.
	<br /><br />
	<h3>What Are Digital Certificates ?</h3>
	Your certificates are digital identities that are equivalent to your 
	normal ID (e.g., your driving license, passport or school/employer 
	ID card), but in a digital format that can be used on computers and 
	on the Internet.
	Digital certificates can be issued to people and/or computer servers
	and are commonly used for many purposes:
<ul>
<li><b>Secure Email</b> - for digital signing and encryption of email</li>
<li><b>Document Signing</b> - including PDF and Office documents</li>
<li><b>Secure Networ Access</b> - to provide a much higher level of security
than username/password (eg., for Wireless access)</li>
<li><b>Server Authentication (https)</b> - to protect the communication with
a Web server (eg., for online banking or eCommerce)</li>
</ul>
  </p>
  <p>
  <h3>How Do I Get A Digital Certificate ?</h3>
  Getting your certificate is as easy as saying 1.. 2.. 3! Follow the
  steps and use your new digital identity to secure your data and your
  communication over the Internet!
  </p>
  </div>

  @CONTROL_PANEL@

</div> 

@NOTICES_PANEL@

