Sehr geehrte Eigentümerin, sehr geehrter Eigentümer des Zertifikates __CERT_SERIAL__,

das Zertifikat mit der Seriennummer __CERT_SERIAL__ und dem Name
__CERT_SUBJECT__ wird um __CERT_NOTAFTER__ ablaufen. Das Zertifikat wurde für
__CERT_CN__ ausgestellt.

Bitte besuchen Sie unsere Web-Seite, um ein neues Zertifikat zu beantragen oder
kontaktieren Sie Ihre Registrierungsstelle für die Erneuerung Ihres Zertifikates.
Sie könne auch einfach auf diese E-Mail antworten, um weitere Informationen zu erhalten.

@httpd_protocol@://@httpd_host@@httpd_port@

Bitte beachten Sie, dass die Anwendungen und Dienste, für die dieses Zertifikat
benutzt wird, wahrscheinlich nicht mehr nutzbar sind, wenn das Zertifikat abgelaufen ist.


Mit freundlichen Grüßen

Ihr @ca_organization@ PKI-Team
