Witam!


Przypominam, że certyfikat o numerze seryjnym __CERT_SERIAL__
wydany dla __CERT_DN__
(__CERT_SUBJECT__)
wygasa z dniem __CERT_NOAFTER__.

Aby  ponownie złożyć zlecenie certyfikacji, odwiedź naszą witrynę.
@httpd_protocol@://@httpd_host@@httpd_port@

Jeśli chcesz odnowić certyfikat, skontaktuj się z naszym
Centrum Rejestracyjnym.

Aby uzyskać więcej informacji odpisz na tą wiadomość.

Pamiętaj o tym, że usługi, w których wykorzystujesz certyfikat mogą
przestać funkcjonować poprawnie po wygaśnięciu certyfikatu.


Pozdrawiam

Operator
