=head1 NAME

OpenCA::XML::Cache - Perl module to cache the configuration files of OpenCA .

=head1 SYNOPSIS

use OpenCA::XML::Cache;

=head1 DESCRIPTION

Sorry, no documentation available yet. The module is not complete until now.

=head1 AUTHOR

Michael Bell <michael.bell@web.de>

=head1 SEE ALSO

perl(1).

=cut
