Dear Owner of Certificate __CERT_SERIAL__,

the certificate with the serial __CERT_SERIAL__ and the subject
__CERT_SUBJECT__ will expiring at __CERT_NOTAFTER__.
The certificate was issued for __CERT_CN__.

Please visit our webpage to request a new certificate or
contact your registration authority to renew the certificate.
You can simply reply to this email for further informations.

@httpd_protocol@://@httpd_host@@httpd_port@

Please remember that the services for which the certificate
is used will propably no longer usable if the certificate
is expired.

				Sincerily Yours, 
				@ca_organization@ Security Staff.
