Dear Owner of Certificate __CERT_SERIAL__,

The certificate with the serial __CERT_SERIAL__ and the subject
__CERT_SUBJECT__ will expire at __CERT_NOTAFTER__.
The certificate was issued for __CERT_CN__.

Please visit our webpage to request a new certificate or
contact your registration authority to renew the certificate.
You can simply reply to this email for further information.

@httpd_protocol@://@httpd_host@@httpd_port@

Please remember that the services for which the certificate
is used will probably no longer be usable once the certificate
expires.

				Sincerely Yours, 
				@ca_organization@ Security Staff.
